id: P009149
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W22201
  title: ཨོ་རྒྱན་གླིང་གི་དཀར་ཆག
  author: ''
  volumes:
    addf1a3c30b747359bca9d2fa150b812:
      image_group_id: I3633
      title: ''
      volume_number: 1
      total_pages: 234
      base_file: v001.txt
